{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.database.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if eq (.Values.database.type) "internal" }}
  username: {{ .Values.database.internal.auth.username | b64enc | quote }}
  password: {{ .Values.database.internal.auth.password | b64enc | quote }}
  {{- else if eq (.Values.database.type) "external" }}
  username: {{ .Values.database.external.auth.username | b64enc | quote }}
  password: {{ .Values.database.external.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
