{{- if not .Values.core.openai.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.core.openai.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  api-key: {{ .Values.core.openai.apiKey | b64enc | quote }}
{{- end }}
