apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.core.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  NODE_ENV: {{ .Values.core.nodeEnv | default "production" | quote }}
  MAILER_NAME: {{ .Values.core.transport.name | quote }}
  MAILER_HOST: {{ .Values.core.transport.host | quote }}
  MAILER_PORT: {{ .Values.core.transport.port | quote }}
  MAILER_SECURE: {{ .Values.core.transport.secure | quote }}

