{{- if not .Values.oauth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.oauth.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  google-client-id: {{ .Values.oauth.google.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.oauth.google.clientSecret | b64enc | quote }}
{{- end }}
