{{- if not .Values.session.storage.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.session.storage.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  redis-password: {{ .Values.session.storage.auth.password | b64enc | quote }}
{{- end }}
