{{- if not .Values.cookie.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.cookie.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  secret: {{ .Values.cookie.secret | default (randAlphaNum 64) | b64enc }}
{{- end }}
