{{- if not .Values.database.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.database.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.database.auth.username | b64enc | quote }}
  password: {{ .Values.database.auth.password | b64enc | quote }}
{{- end }}
