apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  PORT: {{ .Values.service.targetPort | quote }}
  CORS_ORIGIN: {{ .Values.cors.origin | quote }}
  COOKIE_DOMAIN: {{ .Values.cookie.domain | quote }}
  SESSION_NAME: {{ .Values.session.name | quote }}
  SESSION_TIMEOUT: {{ .Values.session.timeout | quote }}
  AUTO_MAILER_URL: {{ .Values.autoMailer.url | quote }}
  VERIFY_EMAIL_URL: {{ .Values.autoMailer.verifyEmailUrl | quote }}
  JWT_EXPIRES_IN_ACCESS: {{ .Values.jwt.access.expiresIn | quote }}
  JWT_EXPIRES_IN_REFRESH: {{ .Values.jwt.refresh.expiresIn | quote }}
  JWT_EXPIRES_IN_EMAIL_VERIFICATION: {{ .Values.jwt.emailVerification.expiresIn | quote }}
  SESSION_STORAGE_HOST: {{ .Values.session.storage.host | quote }}
  SESSION_STORAGE_PORT: {{ .Values.session.storage.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
