apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mandacode-auth.fullname" . }}
  labels:
    {{- include "mandacode-auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mandacode-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configmap.checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mandacode-auth.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mandacode-auth.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: prisma-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "core.configMapName" . }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "core.configMapName" . }}
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "core.configMapName" . }}
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.database.secretName" . }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.database.secretName" . }}
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"

      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "core.configMapName" . }}
          env:
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.cookie.secretName" . }}
                  key: secret
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "core.configMapName" . }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "core.configMapName" . }}
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "core.configMapName" . }}
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.database.secretName" . }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.database.secretName" . }}
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
            - name: SESSION_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.session.storage.secretName" . }}
                  key: redis-password
            - name: JWT_PUBLIC_ACCESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.jwt.access.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_ACCESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.jwt.access.secretName" . }}
                  key: private
            - name: JWT_PUBLIC_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.jwt.refresh.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_REFRESH
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.jwt.refresh.secretName" . }}
                  key: private
            - name: JWT_PUBLIC_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.jwt.emailVerification.secretName" . }}
                  key: public
            - name: JWT_PRIVATE_EMAIL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.jwt.emailVerification.secretName" . }}
                  key: private
            - name: OAUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.oauth.secretName" . }}
                  key: google-client-id
            - name: OAUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.oauth.secretName" . }}
                  key: google-client-secret
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
