{{- if not .Values.global.database.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.global.database.auth.username | b64enc | quote }}
  password: {{ .Values.global.database.auth.password | b64enc | quote }}
  postgres-password: {{ .Values.global.database.auth.postgresPassword | b64enc | quote }}
{{- end }}

