{{- if not .Values.global.session.storage.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: session-storage-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  redis-password: {{ .Values.global.session.storage.auth.password | b64enc | quote }}
{{- end }}
