{{- if not .Values.gateway.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.gateway.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  jwt-secret: {{ .Values.gateway.jwtSecret | b64enc | quote }}
{{- end }}
