# values.yaml for APISIX Routes and TLS
global:
  namespace: default
  labels:
    app: apisix
    environment: production
  annotations:
    app.kubernetes.io/managed-by: argocd

# Service Account configuration
serviceAccount:
  create: true
  name: "apisix-routes-manager"
  annotations: {}

# APISIX Routes configuration
routes:
  # auth-temp.mandacode.com/api/core -> mandacode-accounts-mandacode-auth service in mandacode-accounts namespace
  - name: mandacode-accounts-mandacode-auth
    enabled: true
    namespace: mandacode-accounts
    hosts:
      - auth.mandacode.com
    paths:
      - "/api/core/*"
      - "/api/core"
    upstream:
      serviceName: mandacode-accounts-mandacode-auth
      servicePort: 80
    plugins:
      - name: proxy-rewrite
        config:
          regex_uri: ["^/api/core(/.*)?$", "$1"]
    labels:
      app: mandacode-accounts
      component: mandacode-auth
    annotations:
      description: "Authentication service route"

  # saju.mandacode.com/api/core -> saju-core service in saju namespace
  - name: saju-core
    enabled: true
    namespace: saju
    hosts:
      - saju.mandacode.com
    paths:
      - "/api/core/*"
      - "/api/core"
    upstream:
      serviceName: saju-core
      servicePort: 80
    plugins:
      - name: proxy-rewrite
        config:
          regex_uri: ["^/api/core(/.*)?$", "$1"]
      - name: cors
        config:
          allow_origins: "*"
          allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
          allow_headers: "Authorization,Content-Type,Accept"
          max_age: 3600
    labels:
      app: saju
      component: core
    annotations:
      description: "Saju core service route"

  - name: grafana-route
    enabled: true
    namespace: cilium-monitoring
    hosts:
      - grafana.mandacode.com
    paths:
      - "/*"
      - "/"
    upstream:
      serviceName: grafana
      servicePort: 3000
    labels:
      app: monitoring
      component: grafana
    annotations:
      description: "Grafana service route"

ssl:
  - name: mandacode-tls
    enabled: true
    namespace: default
    secretName: mandacode-tls
    hosts:
      - auth.mandacode.com
      - saju.mandacode.com
      - grafana.mandacode.com
