# values.yaml for APISIX Routes and TLS
global:
  namespace: default
  labels:
    app: apisix
    environment: production
  annotations:
    app.kubernetes.io/managed-by: argocd

# Service Account configuration
serviceAccount:
  create: true
  name: "apisix-routes-manager"
  annotations: {}

# APISIX Routes configuration
routes:
  # argocd.mandacode.com -> argocd-server service in argocd namespace
  - name: argocd
    enabled: true
    namespace: argocd
    hosts:
      - argocd.mandacode.com
    paths:
      - "/*"
      - "/"
    upstream:
      serviceName: argocd-server
      servicePort: 80
    plugins:
      - name: proxy-rewrite
        config:
          regex_uri: ["^/api(/.*)?$", "$1"]
    labels:
      app: argocd-server
      component: argocd
    annotations:
      description: "ArgoCD server route"

  # # auth-temp.mandacode.com/api/core -> mandacode-accounts-mandacode-auth service in mandacode-accounts namespace
  # - name: mandacode-accounts-mandacode-auth
  #   enabled: true
  #   namespace: mandacode-accounts
  #   hosts:
  #     - auth.mandacode.com
  #   paths:
  #     - "/api/core/*"
  #     - "/api/core"
  #   upstream:
  #     serviceName: mandacode-accounts-mandacode-auth
  #     servicePort: 80
  #   plugins:
  #     - name: proxy-rewrite
  #       config:
  #         regex_uri: ["^/api/core(/.*)?$", "$1"]
  #   labels:
  #     app: mandacode-accounts
  #     component: mandacode-auth
  #   annotations:
  #     description: "Authentication service route"
  #
  # # saju.mandacode.com/api/core -> saju-core service in saju namespace
  # - name: saju
  #   enabled: true
  #   namespace: saju
  #   hosts:
  #     - saju.mandacode.com
  #   paths:
  #     - "/api/core/*"
  #     - "/api/core"
  #   upstream:
  #     serviceName: saju
  #     servicePort: 80
  #   plugins:
  #     - name: proxy-rewrite
  #       config:
  #         regex_uri: ["^/api/core(/.*)?$", "$1"]
  #     - name: cors
  #       config:
  #         allow_origins: "*"
  #         allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  #         allow_headers: "Authorization,Content-Type,Accept"
  #         max_age: 3600
  #   labels:
  #     app: saju
  #     component: saju
  #   annotations:
  #     description: "Saju core service route"

customPlugins:
  - name: rsa-jwt
    description: "RSA JWT verify plugin"
    targetRoutes:
      - saju
    config:
      enable: true
      force_auth: true
      gateway_auth_header: "X-Gateway-Verified"
      public_key: ""
      hmac_secret: ""
      exposed_payload_keys:
        - uuid
        - role

ssl:
  - name: mandacode-tls
    enabled: true
    namespace: default
    secretName: mandacode-tls
    hosts:
      - argocd.mandacode.com
      - auth.mandacode.com
      - saju.mandacode.com
