# values.yaml for APISIX Routes and TLS
global:
  namespace: default
  labels:
    app: apisix
    environment: production
  annotations:
    app.kubernetes.io/managed-by: argocd

# Service Account configuration
serviceAccount:
  create: true
  name: "apisix-routes-manager"
  annotations: {}

# APISIX Routes configuration
routes:
  # registry.mandacode.com -> harbor service in registry namespace
  - name: harbor-ui
    enabled: true
    namespace: registry
    hosts:
      - registry.mandacode.com
    paths:
      - "/*"
      - "/"
      - "/index.html"
      - "/favicon.ico"
      - "/static/*"
    upstream:
      serviceName: harbor-portal
      servicePort: 80
    labels:
      app: harbor-portal
      component: harbor
    annotations:
      description: "Harbor UI route"

  # registry.mandacode.com/api -> harbor service in registry namespace
  - name: harbor-api
    enabled: true
    namespace: registry
    hosts:
      - registry.mandacode.com
    paths:
      - "/api/*"
      - "/api/"
      - "/c/*"
      - "/c/"
      - "/service/*"
      - "/service/"
    upstream:
      serviceName: harbor-core
      servicePort: 80
    labels:
      app: harbor-core
      component: harbor
    annotations:
      description: "Harbor API route"

  # registry.mandacode.com/v2 -> harbor service in registry namespace
  - name: harbor-registry
    enabled: true
    namespace: registry
    hosts:
      - registry.mandacode.com
    paths:
      - "/v2/*"
      - "/v2"
    upstream:
      serviceName: harbor-registry
      servicePort: 5000
    labels:
      app: harbor-registry
      component: harbor
    plugins:
      - name: proxy-rewrite
        config:
          headers:
            Authorization: "$http_authorization"
    annotations:
      description: "Harbor registry route"

  # # auth-temp.mandacode.com/api/core -> mandacode-accounts-mandacode-auth service in mandacode-accounts namespace
  # - name: mandacode-accounts-mandacode-auth
  #   enabled: true
  #   namespace: mandacode-accounts
  #   hosts:
  #     - auth.mandacode.com
  #   paths:
  #     - "/api/core/*"
  #     - "/api/core"
  #   upstream:
  #     serviceName: mandacode-accounts-mandacode-auth
  #     servicePort: 80
  #   plugins:
  #     - name: proxy-rewrite
  #       config:
  #         regex_uri: ["^/api/core(/.*)?$", "$1"]
  #   labels:
  #     app: mandacode-accounts
  #     component: mandacode-auth
  #   annotations:
  #     description: "Authentication service route"
  #
  # # saju.mandacode.com/api/core -> saju-core service in saju namespace
  # - name: saju
  #   enabled: true
  #   namespace: saju
  #   hosts:
  #     - saju.mandacode.com
  #   paths:
  #     - "/api/core/*"
  #     - "/api/core"
  #   upstream:
  #     serviceName: saju
  #     servicePort: 80
  #   plugins:
  #     - name: proxy-rewrite
  #       config:
  #         regex_uri: ["^/api/core(/.*)?$", "$1"]
  #     - name: cors
  #       config:
  #         allow_origins: "*"
  #         allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  #         allow_headers: "Authorization,Content-Type,Accept"
  #         max_age: 3600
  #   labels:
  #     app: saju
  #     component: saju
  #   annotations:
  #     description: "Saju core service route"

customPlugins:
  - name: rsa-jwt
    description: "RSA JWT verify plugin"
    targetRoutes:
      - saju
    config:
      enable: true
      force_auth: true
      gateway_auth_header: "X-Gateway-Verified"
      public_key: ""
      hmac_secret: ""
      exposed_payload_keys:
        - uuid
        - role

ssl:
  - name: mandacode-tls
    enabled: true
    namespace: default
    secretName: mandacode-tls
    hosts:
      - argocd.mandacode.com
      - registry.mandacode.com
      - auth.mandacode.com
      - saju.mandacode.com
