# values.yaml for APISIX Routes and TLS
global:
  namespace: default
  labels:
    app: apisix
    environment: production
  annotations:
    app.kubernetes.io/managed-by: argocd

# Service Account configuration
serviceAccount:
  create: true
  name: "apisix-routes-manager"
  annotations: {}

# APISIX Routes configuration
routes:
  # argocd.mandacode.com -> argocd-server service in argocd namespace
  - name: argocd
    enabled: true
    namespace: argocd
    hosts:
      - argocd.mandacode.com
    paths:
      - "/*"
      - "/"
    upstream:
      serviceName: argocd-server
      servicePort: 80
    labels:
      app: argocd-server
      component: argocd
    annotations:
      description: "ArgoCD server route"

    # auth.mandacode.com/api/core -> mandacode-auth service in mandacode-auth namespace
  - name: mandacode-auth
    enabled: true
    namespace: mandacode-auth
    hosts:
      - auth.mandacode.com
    paths:
      - "/api/core/*"
      - "/api/core"
    upstream:
      serviceName: mandacode-auth
      servicePort: 80
    plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/api/core(/.*)?$", "$1"]
    labels:
      app: mandacode-auth
      component: mandacode-auth
    annotations:
      description: "Authentication service route"

  # saju.mandacode.com/api/core -> saju-core service in saju namespace
  - name: saju
    enabled: true
    namespace: saju
    hosts:
      - saju.mandacode.com
    paths:
      - "/api/core/*"
      - "/api/core"
    upstream:
      serviceName: saju
      servicePort: 80
    plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/api/core(/.*)?$", "$1"]
      - name: cors
        enable: true
        config:
          allow_origins: "*"
          allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
          allow_headers: "Authorization,Content-Type,Accept"
          max_age: 3600
      - name: rsa-jwt
        enable: true
        secretRef: rsa-jwt-secret
        config:
          force_auth: true
          gateway_jwt_header: "X-Gateway-JWT"
          gateway_jwt_exp: 30
          gateway_jwt_iss: "api-gateway"
          gateway_jwt_aud: "saju"
          payload_keys:
            - "uuid"
            - "role"
    labels:
      app: saju
      component: saju
    annotations:
      description: "Saju core service route"

secrets:
  - name: rsa-jwt-secret
    namespaces:
      - saju
    data:
      access_public_key: ""
      gateway_jwt_secret: ""

ssl:
  - name: mandacode-tls
    enabled: true
    namespace: default
    secretName: mandacode-tls
    hosts:
      - argocd.mandacode.com
      - auth.mandacode.com
      - saju.mandacode.com
