apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saju.database.secretName" . }}
  labels:
    app: saju
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
