{{- range $route := .Values.routes }}
{{- if $route.enabled }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $route.name }}
  namespace: {{ $route.namespace | default $.Values.global.namespace | default "default" }}
  labels:
    {{- include "apisix-routes-tls.labels" $ | nindent 4 }}
    {{- with $.Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  http:
    - name: {{ $route.name }}
      match:
        hosts:
          {{- range $route.hosts }}
          - {{ . }}
          {{- end }}
        paths:
          {{- range $route.paths }}
          - {{ . }}
          {{- end }}
      backends:
        - serviceName: {{ $route.upstream.serviceName }}
          servicePort: {{ $route.upstream.servicePort }}
          {{- if $route.upstream.scheme }}
          scheme: {{ $route.upstream.scheme }}
          {{- end }}
      plugins:
        {{- range $route.plugins }}
        - name: {{ .name }}
          enable: true
          {{- if .config }}
          config:
            {{- toYaml .config | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- range $plugin := $.Values.customPlugins }}
        {{- if has $route.name $plugin.targetRoutes }}
        - name: {{ $plugin.name }}
          enable: true
          config:
            {{- toYaml $plugin.config | nindent 12 }}
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}
