{{- range .Values.routes }}
{{- if .enabled }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Values.global.namespace | default "default" }}
  labels:
    {{- include "apisix-routes-tls.labels" $ | nindent 4 }}
    {{- with $.Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  http:
    - name: {{ .name }}
      match:
        hosts:
          {{- range .hosts }}
          - {{ . }}
          {{- end }}
        paths:
          {{- range .paths }}
          - {{ . }}
          {{- end }}
      backends:
        - serviceName: {{ .upstream.serviceName }}
          servicePort: {{ .upstream.servicePort }}
          {{- if .upstream.scheme }}
          scheme: {{ .upstream.scheme }}
          {{- end }}
      {{- if .plugins }}
      plugins:
        {{- range .plugins }}
        - name: {{ .name }}
          enable: true
          {{- if .config }}
          config:
            {{- toYaml .config | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
