{{- range .Values.secrets }}
  {{- $secret := . }}
  {{- range $ns := .namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- range $key, $val := $secret.data }}
  {{ $key }}: {{ $val | default "" | quote }}
  {{- end }}
---
  {{- end }}
{{- end }}
