{{- if $secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- range $key, $val := $secret.data }}
  {{- if $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
