
# ssl:
#   - name: mandacode-tls
#     enabled: true
#     namespace: default
#     secretName: mandacode-tls
#     hosts:
#       - auth.mandacode.com
#       - saju.mandacode.com
{{/* Route-specific TLS settings */}}

{{- range .Values.ssl }}
{{- if .enabled }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Values.global.namespace | default "default" }}
  labels:
    {{- include "apisix-routes-tls.labels" $ | nindent 4 }}
    {{- with $.Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  secret:
    name: {{ .secretName }}
    namespace: {{ .namespace }}
  {{- if .client }}
  client:
    {{- toYaml .client | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
