{{- if not .Values.core.cookie.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.core.cookie.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  secret: {{ .Values.core.cookie.secret | default (randAlphaNum 64) | b64enc }}
{{- end }}
