{{- if not .Values.core.oauth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.core.oauth.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  google-client-id: {{ .Values.core.oauth.google.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.core.oauth.google.clientSecret | b64enc | quote }}
  kakao-client-id: {{ .Values.core.oauth.kakao.clientId | b64enc | quote }}
  kakao-client-secret: {{ .Values.core.oauth.kakao.clientSecret | b64enc | quote }}
  naver-client-id: {{ .Values.core.oauth.naver.clientId | b64enc | quote }}
  naver-client-secret: {{ .Values.core.oauth.naver.clientSecret | b64enc | quote }}
{{- end }}
