{{- if .Values.core.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.core.serviceAccountName" . }}
  labels:
    {{- include "app.core.labels" . | nindent 4 }}
  {{- with .Values.core.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.core.serviceAccount.automount }}
{{- end }}
