{{- if not .Values.core.transport.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.core.transport.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.core.transport.auth.username | b64enc | quote }}
  password: {{ .Values.core.transport.auth.password | b64enc | quote }}
{{- end }}
