apiVersion: v2
name: mandacode-auth
description: Mandacode Auth Service Helm Chart
type: application
version: 0.1.3
dependencies:
  - name: mailer
    alias: mailer
    version: 0.1.1-rc1
    repository: "oci://registry.mandacode.com/mailer/charts"
    condition: mailer.enabled
