{{- if not .Values.tokenService.jwt.existingSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.tokenService.jwt.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  jwt-public-access: {{ .Values.tokenService.jwt.access.publicKey | b64enc | quote }}
  jwt-private-access: {{ .Values.tokenService.jwt.access.privateKey | b64enc | quote }}
  jwt-public-refresh: {{ .Values.tokenService.jwt.refresh.publicKey | b64enc | quote }}
  jwt-private-refresh: {{ .Values.tokenService.jwt.refresh.privateKey | b64enc | quote }}
  jwt-public-email-verification: {{ .Values.tokenService.jwt.emailVerification.publicKey | b64enc | quote }}
  jwt-private-email-verification: {{ .Values.tokenService.jwt.emailVerification.privateKey | b64enc | quote }}
{{- end }}

