{{- if .Values.tokenService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.tokenService.serviceAccountName" . }}
  labels:
    {{- include "app.tokenService.labels" . | nindent 4 }}
  {{- with .Values.tokenService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.tokenService.serviceAccount.automount }}
{{- end }}
