apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.tokenService.fullname" . }}
  labels:
    {{- include "app.tokenService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tokenService.service.type }}
  ports:
    - port: {{ .Values.tokenService.service.port }}
      targetPort: {{ .Values.tokenService.service.targetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "app.tokenService.selectorLabels" . | nindent 4 }}
