global:
  database:
    auth:
      existingSecret: ""
      username: "postgres"
      password: "password"
      postgresPassword: "password"
  session:
    storage:
      auth:
        existingSecret: ""
        password: "password"

# MANDACODE-AUTH
mandacode-auth:
  replicaCount: 1

  image:
    repository: registry.mandacode.com/mandacode/accounts/auth-core
    pullPolicy: IfNotPresent
    tag: "0.1.1"

  imagePullSecrets:
    - name: regcred

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources: {}

  livenessProbe:
    httpGet:
      path: /health
      port: 3000
  readinessProbe:
    httpGet:
      path: /health
      port: 3000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  volumes: []

  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  core:
    configMapName: ""

  database:
    host: "localhost"
    port: 5432
    name: "auth"
    auth:
      existingSecret: "database-secret"
      username: ""
      password: ""

  cors:
    origin: "https://auth.mandacode.com"

  cookie:
    secretName: ""
    secret: ""
    domain: "mandacode.com"

  session:
    name: "SID"
    timeout: 86400
    storage:
      host: "localhost"
      port: 6379
      auth:
        existingSecret: "session-storage-secret"
        password: ""

  autoMailer:
    host: ""
    port: 50051
    verifyEmailUrl: "https://auth.mandacode.com/auth/local/verify-email"

  jwt:
    access:
      secretName: ""
      expiresIn: "15m"
    refresh:
      secretName: ""
      expiresIn: "7d"
    emailVerification:
      secretName: ""
      expiresIn: "1d"

  oauth:
    existingSecret: ""
    google:
      endpoints:
        token: "https://oauth2.googleapis.com/token"
        profile: "https://www.googleapis.com/oauth2/v3/userinfo"
        auth: "https://accounts.google.com/o/oauth2/v2/auth"
      grantType: "authorization_code"
      clientId: ""
      clientSecret: ""
      redirectUri: ""

# AUTO-MAILER
auto-mailer:
  replicaCount: 1

  image:
    repository: registry.mandacode.com/mailer/auto-mailer
    pullPolicy: IfNotPresent
    tag: "0.1.0"
    host: "0.0.0.0"
    port: 3000

  imagePullSecrets:
    - name: regcred

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 50051
    targetPort: 3000

  resources: {}

  livenessProbe:
    exec:
      command:
        - /bin/grpc_health_probe
        - -addr=:3000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  mailer:
    host: smtp.zoho.com
    port: 465
    secure: true
    user: ""
    pass: ""

postgresql:
  enabled: true
  auth:
    username: ""
    password: ""
    existingSecret: "database-secret"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"

redis:
  enabled: true
  auth:
    password: ""
    existingSecret: "session-storage-secret"
