{{- if eq .Values.database.type "internal" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.internal.host }}
spec:
  selector:
    app: {{ .Values.database.internal.host }}
  ports:
    - port: {{ .Values.database.internal.port }}
      targetPort: 5432
{{- end }}
