{{- if eq .Values.session.storage.type "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.session.storage.internal.host }}
  annotations:
    sessionStorageSecret.checksum: {{ include (print $.Template.BasePath "/secrets/session-storage.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.session.storage.internal.host }}
  template:
    metadata:
      labels:
        app: {{ .Values.session.storage.internal.host }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.session.storage.internal.image }}
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.session.storage.secretName" . }}
                  key: redis-password
          ports:
            - containerPort: 5432
{{- end }}
