{{- if not .Values.session.storage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.session.storage.secretName" . }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if eq (.Values.session.storage.type) "internal" }}
  redis-password: {{ .Values.session.storage.internal.auth.password | b64enc | quote }}
  {{- else if eq (.Values.session.storage.type) "external" }}
  redis-password: {{ .Values.session.storage.external.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
